# TWO SAMPLE T - TEST

In [4]:
import numpy as np
from scipy import stats

In [5]:
G_A = [85,88,90,92,87,85,89,91,86,88]
G_B = [82,84,80,83,81,79,78,85,84,83]

In [8]:
t_stats , p_value = stats.ttest_ind(G_A , G_B , equal_var = False )
print(t_stats)

5.829604009507161

In [9]:
alpha = 0.05
if p_value < alpha:
    print("I will reject the null hypothesis")
else:
    print("I will accept the null hypothesis")

I will reject the null hypothesis

# Chi Square

In [13]:
import numpy as np
import seaborn as sns
from scipy.stats import chi2_contingency
import pandas as pd

In [14]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [15]:
contingency_table = pd.crosstab(df['sex'],df['survived'])

In [16]:
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [16]:
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [17]:
chi2,p_value,dof,expected = chi2_contingency(contingency_table)

In [18]:
dof

1

In [20]:
print(p_value)

1.1973570627755645e-58

In [21]:
print(expected)

[[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [22]:
print(chi2)

260.71702016732104

In [23]:
alpha = 0.05
if p_value < alpha:
    print("I will reject the null hypothesis")
else:
    print("I will accept the null hypothesis")

I will reject the null hypothesis